/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uninove.cienciadacomputacao;
import uninove.cienciadacomputacao.calculonumerico.ajustedereta.TelaAjusteDeReta;
import uninove.cienciadacomputacao.calculonumerico.bisseccao.Bisseccao;
import uninove.cienciadacomputacao.calculonumerico.bisseccao.TelaBisseccao;
import uninove.cienciadacomputacao.calculonumerico.coeficientedepearson.TelaCoeficienteDePearson;
import uninove.cienciadacomputacao.calculonumerico.lagrange.TelaLagrange;

/**
 *
 * @author Supervisor
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(28, 72, 101));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAjusteReta = new javax.swing.JButton();
        btnPearson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLagrange = new javax.swing.JButton();
        btnBiseccao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ciência da Computação - 2015 - Walfrido Oliveira da Silva");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        btnAjusteReta.setBackground(new java.awt.Color(204, 204, 204));
        btnAjusteReta.setText("Ajuste de Reta");
        btnAjusteReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjusteRetaActionPerformed(evt);
            }
        });

        btnPearson.setText("Coeficiente de Pearson");
        btnPearson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPearsonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_central_aluno.png"))); // NOI18N

        btnLagrange.setText("Lagrange");
        btnLagrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagrangeActionPerformed(evt);
            }
        });

        btnBiseccao.setText("Bisecção");
        btnBiseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiseccaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnAjusteReta)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLagrange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPearson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnBiseccao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPearson)
                            .addComponent(btnAjusteReta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLagrange))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(btnBiseccao)
                    .addGap(40, 40, 40)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPearsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPearsonActionPerformed
        // TODO add your handling code here:e
        TelaCoeficienteDePearson coeficienteDePearson = new TelaCoeficienteDePearson();
        coeficienteDePearson.setVisible(true);
    }//GEN-LAST:event_btnPearsonActionPerformed

    private void btnAjusteRetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjusteRetaActionPerformed
        // TODO add your handling code here:
        TelaAjusteDeReta ajusteDeTela = new TelaAjusteDeReta();
        ajusteDeTela.setVisible(true);
    }//GEN-LAST:event_btnAjusteRetaActionPerformed

    private void btnLagrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagrangeActionPerformed
        // TODO add your handling code here:
        TelaLagrange lagrande = new TelaLagrange();
        lagrande.setVisible(true);
    }//GEN-LAST:event_btnLagrangeActionPerformed

    private void btnBiseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiseccaoActionPerformed
        // TODO add your handling code here:
        TelaBisseccao b = new TelaBisseccao();
        b.setVisible(true);
                
    }//GEN-LAST:event_btnBiseccaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjusteReta;
    private javax.swing.JButton btnBiseccao;
    private javax.swing.JButton btnLagrange;
    private javax.swing.JButton btnPearson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
